apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aradix-webhook-manager-rolebinding
  namespace: radix-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: radix-webhook-manager-role
subjects:
- kind: ServiceAccount
  name: radix-webhook-admin
  namespace: radix-system
