apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: radix-webhook-manager-role
  namespace: radix-system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
